# Generated by Django 2.2.8 on 2020-02-25 13:09

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('sportwear', 'Sport wear'), ('outwear', 'Outwear')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image_cover',
            field=models.ImageField(default=datetime.datetime(2020, 2, 25, 13, 8, 25, 404410, tzinfo=utc), upload_to='products/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger')], default=datetime.datetime(2020, 2, 25, 13, 9, 20, 795647, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
