# Generated by Django 2.2.8 on 2020-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200225_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='associated_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='_item_associated_items_+', to='core.Item'),
        ),
    ]
