# Generated by Django 2.2.8 on 2020-02-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_associated_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
