# Generated by Django 2.2.8 on 2020-02-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200225_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordereditems', to='core.Item'),
        ),
    ]
