# Generated by Django 2.2.8 on 2020-02-28 07:47

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200228_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='countries',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default=datetime.datetime(2020, 2, 28, 7, 47, 16, 474574, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
